version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: scrapydb
      POSTGRES_USER: scrapyuser
      POSTGRES_PASSWORD: scrapysecret
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U youruser -d yourdb']
      interval: 5s
      timeout: 5s
      retries: 5
  scrapy:
    build:
      context: .
      dockerfile: Dockerfile.scrapy
    environment:
      POSTGRES_DB: yourdb
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./myproject:/app

volumes:
  postgres_data:
