FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy entire project
COPY . .

# Default command (can override when running)
CMD ["scrapy", "crawl", "taraxacum", "-a", "url=https://en.wikipedia.org/wiki/YourPage"] 